-- Query 1: Display doctors with their department names

SELECT
    d.Employee_ID,
    e.First_Name,
    e.Last_Name,
    d.Specialization,
    d.Consultation_Fee,
    dep.Department_Name
FROM Doctor d
JOIN Employee e
    ON d.Employee_ID = e.Employee_ID
JOIN Department dep
    ON e.Department_ID = dep.Department_ID
ORDER BY dep.Department_Name;


-- Query 2: Patients who attended more than one appointment

SELECT
    p.Patient_ID,
    p.First_Name,
    p.Last_Name,
    COUNT(a.Appointment_ID) AS Appointment_Count
FROM Patient p
JOIN Appointment a
    ON p.Patient_ID = a.Patient_ID
WHERE a.Status = 'Completed'
GROUP BY
    p.Patient_ID,
    p.First_Name,
    p.Last_Name
HAVING COUNT(a.Appointment_ID) > 1;


-- Query 3: Total billing amount generated by each department

SELECT
    dep.Department_ID,
    dep.Department_Name,
    SUM(b.Charges) AS Total_Billing
FROM Department dep
JOIN Employee e
    ON dep.Department_ID = e.Department_ID
JOIN Doctor d
    ON e.Employee_ID = d.Employee_ID
JOIN Appointment a
    ON d.Employee_ID = a.Doctor_ID
JOIN Billing b
    ON a.Appointment_ID = b.Appointment_ID
GROUP BY
    dep.Department_ID,
    dep.Department_Name
ORDER BY Total_Billing DESC;


-- Query 4: Doctor with the highest consultation fee

SELECT
    d.Employee_ID,
    e.First_Name,
    e.Last_Name,
    d.Specialization,
    d.Consultation_Fee
FROM Doctor d
JOIN Employee e
    ON d.Employee_ID = e.Employee_ID
WHERE d.Consultation_Fee = (
    SELECT MAX(Consultation_Fee)
    FROM Doctor
);


-- Query 5: Doctors ordered by specialization and consultation fee

SELECT
    d.Employee_ID,
    e.First_Name,
    e.Last_Name,
    d.Specialization,
    d.Consultation_Fee
FROM Doctor d
JOIN Employee e
    ON d.Employee_ID = e.Employee_ID
ORDER BY
    d.Specialization ASC,
    d.Consultation_Fee DESC;